### PR TITLE
Enable $ref to point to other YAML files

### PR DESCRIPTION
**Pull request by tchernobog**
These commits add code to handle references to YAML files in addition to JSON files.

Related to issue #4.

### CODE REVIEW

**Comment by freddrake** [comment]
@tchernobog: Any chance of updating this PR against the current master?

**Comment by tchernobog** [comment]
@freddrake thanks, now it should be rebased.

**Comment by ikalnytskyi** [comment]
Thanks!

**Comment by freddrake** [comment]
With this landed, I can move comfortably to looking at the next problem; progress!  Thank you, @tchernobog.

**Pull request merged**
